### ISSUE TITLE
change addres crytobox

### ISSUE THREAD

**Issue by Axe-Usa** [cryptoapi/Payment-Gateway#21]
trying to change the address but ican't

**Comment by cryptoapi** [comment]
Here how Gourl Gateway works -

Our gateway is based on a different technology than standard gateways. It is fully able to integrate with Internet website pages and is more friendly for use by end website visitors. When any visitor goes to a website page they will see the page content and will see a cryptocoin payment box (For example, Pay-Per-Download). Some websites with high traffic show more than 10,000 pages are viewed per hour and our installed gourl cryptocoin payment box is seen on those pages also. It is impossible for each payment box to show a new unique generated bitcoin payment address for each website visitor because our system would then need to store millions of temporary bitcoin addresses and would be slow in its operation (For example - a 10,000 pages view per hour/payment boxes x 200 high traffic websites with our payment gateway would require no less than 2,000,000 temporary bitcoin addresses).

Therefore, we add to your amount in the payment box a small fraction after the decimal point to uniquely identify each of your visitors individually. This small amount forwarded to you also. Users who have made payments with wrong amount are not recognised and you need to process such payments manually. You can see a separate table above with details of incorrect/unrecognised received payments.
We forward you ALL coins received on your internal wallet address/es including all payments with incorrect amounts (unrecognised payments).


Our system will automatically add an additional new generated internal wallet address to your payment box each time you have received 3 new payments. (This will give you more privacy). So, if you have received 30 cryptocoin payments from your customers you will receive 10 internal wallet addresses for that payment box and for the next payments, customers will see those 10 internal wallet addresses in random order in their cryptocoin payment boxes. So the customer will not know how many total payments you have received. At the same time our gateway stays fully transparent for you and you can see the balance of each of your internal wallet addresses using the external block explorer.
